/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  docs: {
    // "Welcome to MultiversX": ["welcome/welcome-to-multiversx"],
    // "Learn about MultiversX": [
    //   "learn/getting-started",
    //   "learn/multiversx-ecosystem",
    //   "learn/EGLD",
    //   "learn/architecture-overview",
    //   "learn/entities",
    //   "learn/chronology",
    //   "learn/consensus",
    //   "learn/sharding",
    //   "learn/space-vm",
    //   "learn/transactions",
    //   "learn/economics",
    // ],
    Developers: [
      "developers/overview",
      
    ],
    // Validators: [
    //   "validators/overview",
    //   "validators/system-requirements",
    
    //   {
    //     type: "category",
    //     label: "FAQs and Tools",
    //     items: ["validators/faq", "validators/useful-links"],
    //   },
    // ],
    // Integrators: [
    //   "integrators/overview",
    //   {
    //     type: "category",
    //     label: "Integrate EGLD",
    //     items: ["integrators/egld-integration-guide"],
    //   },
    // ],
    // Advanced: [
    //   {
    //     type: "category",
    //     label: "Ad-Astra Bridge",
    //     items: [
    //       "bridge/architecture",
    //       "bridge/transfer-flows",
    //       "bridge/token-types",
    //       "bridge/whitelist-requirements",],
    //   },
      
    // ],
    
  },
};

module.exports = sidebars;
